name: CI

on: [push]

jobs:
  build:

    runs-on: bp-ubuntu-latest-x64-2x

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci

    - run: npm test -- --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json --retries 5

    - name: Upload test results to BuildPulse

      # BuildPulse is most useful when tests FAILED, so run on red builds too.

      if: always()

      uses: BuildPulseLLC/test-reporter-action@v3

      with:

        api-token: ${{ secrets.BUILDPULSE_API_TOKEN }}

        path: .
