name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci

    - run: npm test -- --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json --retries 5

    - name: Upload test results to BuildPulse for flaky test detection
      if: '!cancelled()' # Run this step even when the tests fail. Skip if the workflow is cancelled.
      uses: buildpulse/buildpulse-action@main
      with:
        account: 68192324 # Replace this value with your BuildPulse account ID
        repository: 402774519 # Replace this value with your BuildPulse repository ID
        path: ./test-results.xml
        key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
        secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
